spring:
  application:
    name: portfolio
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/portfolio?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf8&allowPublicKeyRetrieval=true
    username: root
    password: root

app:
  upload-path: D:/uploads/
  upload-url-prefix: /uploads
  upload-date-subdir: true

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto
      table-underline: true
  mapper-locations: classpath*:/mapper/**/*.xml
